import os
from contextlib import asynccontextmanager
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates
from pydantic import BaseModel
from dotenv import load_dotenv
from langchain_core.messages import HumanMessage

# Load env variables (GROQ_API_KEY, POSTGRES_URL)
from pathlib import Path
dotenv_path = Path(__file__).parent / ".env"
load_dotenv(dotenv_path=dotenv_path)

# HTML Templates config
templates = Jinja2Templates(directory=str(Path(__file__).parent / "templates"))

# Import the LangGraph compiled agent and RAG service
from backend.agents.hospital_agent import hospital_agent_app
from backend.services.rag_service import rag_service

# --- Models ---
class ChatRequest(BaseModel):
    user_id: str
    message: str

class ChatResponse(BaseModel):
    response: str

class UpdatePlanRequest(BaseModel):
    # Optional ID. If provided, updates existing rule. If None, makes new rule.
    location_id: str | None = None
    document: str

# --- App Lifecycle ---
@asynccontextmanager
async def lifespan(app: FastAPI):
    if not os.getenv("GROQ_API_KEY"):
        print("WARNING: GROQ_API_KEY is not set. The LLM nodes will fail.")
    yield

# --- FastAPI Setup ---
app = FastAPI(title="Hospital AI Agent API", lifespan=lifespan)

@app.get("/", response_class=HTMLResponse)
async def get_chat_ui(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})

@app.post("/update_floor_plan")
async def update_floor_plan(request: UpdatePlanRequest):
    try:
        doc_id = rag_service.insert_document(request.document, request.location_id)
        return {
            "status": "success", 
            "message": "Floor plan structured successfully.",
            "location_id": doc_id
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.delete("/clear_floor_plan")
async def clear_floor_plan():
    try:
        rag_service.clear_database()
        return {"status": "success", "message": "All floor plan data cleared successfully."}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/chat", response_model=ChatResponse)
async def chat_endpoint(request: ChatRequest):
    try:
        # 1. Initialize TypedDict state for the graph run
        initial_state = {
            "user_id": request.user_id,
            "messages": [HumanMessage(content=request.message)],
            "intent": "",
            "context": ""
        }
        
        # 2. Invoke the compiled LangGraph workflow
        # Thread isolation configuration can be added here if persistence checkpointers are used
        config = {"configurable": {"thread_id": request.user_id}}
        result = hospital_agent_app.invoke(initial_state, config=config)
        
        # 3. Extract the last message (which is the AIMessage generated by response node)
        final_message = result["messages"][-1].content
        
        return ChatResponse(response=final_message)
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
